### ISSUE TITLE
1.18.1 Update

### ISSUE THREAD

**Issue by Samlegamer** [raulsmartin/Food-Expansion#3]
Hello I have ported the whole mod to 1.18.1 @raulsmartin.

Branch: https://github.com/Samlegamer/Food-Expansion/tree/1.18.1

I also added other food such as Goat Meat or Glow Squid.
![2022-01-27_16 50 39](https://user-images.githubusercontent.com/83614614/151394521-14ea8cc9-7b71-4164-b98d-b50c7f867825.png)

Jar file: https://www.mediafire.com/file/emqkmblm15rny8t/foodexpansion-1.18.1-1.0.jar/file

**Comment by raulsmartin** [comment]
OMG Thanks for your dedication! We are currently working on the update and we sadly can't pull this request due to the many changes made on the repository. 😥 However, we will include this items to the mod, cause the seem amazing! We are sorry we weren't able to update officialy the mod until now, but any further ideas can be discussed on the official [Discord Server](https://discord.gg/SNr9Efe).
